Use nightly 2024-09-12 (#2845)
* downgrade rust toolchain

* changelog

* Does this work?

* fix agent?

* macos release

* override rust-toolchain.toml in lint

* whatever

* override toolchain for agent unit tests

* Is  installed?

* Revert installing gcc target.

setup-rust-toolchain said:
error: component 'rust-std' for target 'aarch64-linux-gnu-gcc' is unavailable for download for channel 'nightly-2024-10-11'

This reverts commit 2f5cee3a0ed14b87f95a44fc4922f0a4660f4616.

* fix ci

* ..

* ..

---------

Co-authored-by: Aviram Hassan <aviram@metalbear.co>