Revert installing gcc target.
setup-rust-toolchain said:
error: component 'rust-std' for target 'aarch64-linux-gnu-gcc' is unavailable for download for channel 'nightly-2024-10-11'

This reverts commit 2f5cee3a0ed14b87f95a44fc4922f0a4660f4616.